dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.0

compiler:
  solc:
    version: 0.8.19
    optimizer:
      enabled: true
      runs: 200

networks:
  development:
    host: http://127.0.0.1:7545
    gas_limit: 6721975
    gas_buffer: 1.1
    gas_price: 20000000000
    reverting_tx_gas_limit: false
    default_contract_owner: true

  ganache:
    host: http://127.0.0.1:7545
    gas_limit: 6721975
    gas_buffer: 1.1
    gas_price: 20000000000
    reverting_tx_gas_limit: false
    default_contract_owner: true

  sepolia:
    host: https://sepolia.infura.io/v3/66308c62e2cb49e8bac4b4cd96143144
    chainid: 11155111
    gas_limit: 8000000
    gas_buffer: 1.2
    gas_price: 20000000000
    priority_fee: 2000000000
    max_fee: 30000000000

dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}
